# Generated by Django 5.2 on 2025-04-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyBenchmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=100)),
                ('benchmark_value', models.FloatField(help_text='Standard kWh value for the device')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
