# Generated by Django 5.2 on 2025-04-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0003_utilitybill'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=100)),
                ('issue_identified', models.TextField()),
                ('recommendation', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
