# Generated by Django 5.2 on 2025-04-26 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0004_energyrecommendation'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyRecommendations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=100)),
                ('issue_identified', models.TextField()),
                ('recommendation', models.TextField()),
                ('recommendation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='EnergyRecommendation',
        ),
    ]
