# Generated by Django 5.2 on 2025-05-03 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0005_energyrecommendations_delete_energyrecommendation'),
    ]

    operations = [
        migrations.CreateModel(
            name='RenewableEnergySource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('Solar', 'Solar'), ('Wind', 'Wind'), ('Hydro', 'Hydro')], max_length=20)),
                ('installation_date', models.DateField()),
                ('capacity_kw', models.FloatField(help_text='Installed capacity in kW')),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RenewableEnergyGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation_date', models.DateField()),
                ('energy_generated_kwh', models.FloatField()),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energy.renewableenergysource')),
            ],
        ),
    ]
