# Generated by Django 5.2 on 2025-05-03 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0006_renewableenergysource_renewableenergygeneration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='renewableenergysource',
            name='capacity_kw',
        ),
        migrations.AlterField(
            model_name='renewableenergysource',
            name='installation_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='renewableenergysource',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='renewableenergysource',
            name='source_type',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='RenewableEnergyGeneration',
        ),
    ]
