# Generated by Django 5.2 on 2025-05-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0007_remove_renewableenergysource_capacity_kw_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RenewableEnergyGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('amount_generated', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='renewableenergysource',
            old_name='source_type',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='renewableenergysource',
            name='installation_date',
        ),
        migrations.RemoveField(
            model_name='renewableenergysource',
            name='location',
        ),
    ]
