# Generated by Django 5.2 on 2025-05-04 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0008_renewableenergygeneration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='renewableenergysource',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='renewableenergygeneration',
            name='amount_generated',
            field=models.FloatField(help_text='kWh'),
        ),
        migrations.AlterField(
            model_name='renewableenergygeneration',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energy.renewableenergysource'),
        ),
        migrations.AlterField(
            model_name='renewableenergysource',
            name='name',
            field=models.CharField(choices=[('Solar', 'Solar'), ('Wind', 'Wind'), ('Biomass', 'Biomass'), ('Hydro', 'Hydro')], max_length=100),
        ),
    ]
